version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}    
    volumes: 
        - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
  adminer: # To manage the db
    image: adminer
    restart: always
    ports:
      - 8080:8080